{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pairsd3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pairsD3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pairsD3/pairsD3_{{ version }}.tar.gz
  sha256: f90bf49217af2cece05c394ce3dbe0dee4366aabdfcd5892fe07687a4b4b31f0

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-htmlwidgets >=0.3.2
    - r-shiny
  run:
    - r-base
    - r-htmlwidgets >=0.3.2
    - r-shiny

test:
  commands:
    - $R -e "library('pairsD3')"           # [not win]
    - "\"%R%\" -e \"library('pairsD3')\""  # [win]

about:
  home: http://github.com/garthtarr/pairsD3/
  license: GPL-3.0-or-later
  summary: Creates an interactive scatterplot matrix using the D3 JavaScript library. See <http://d3js.org/> for more information on D3.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pairsD3
# Title: D3 Scatterplot Matrices
# Version: 0.1.0
# Authors@R: person("Garth", "Tarr", , "garth.tarr@gmail.com", role = c("aut", "cre"))
# Description: Creates an interactive scatterplot matrix using the D3 JavaScript library. See <http://d3js.org/> for more information on D3.
# Depends: R (>= 3.1.2)
# License: GPL (>= 3)
# Date: 2015-04-28
# URL: http://github.com/garthtarr/pairsD3/
# LazyData: true
# Imports: htmlwidgets (>= 0.3.2), shiny
# Suggests: knitr
# NeedsCompilation: no
# Packaged: 2015-04-27 23:29:02 UTC; garthtarr
# Author: Garth Tarr [aut, cre]
# Maintainer: Garth Tarr <garth.tarr@gmail.com>
# Repository: CRAN
# Date/Publication: 2015-04-28 06:58:01
