appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 01OQyjJTstFOf3DIi1zeZVLPPYPeb6xwompkeMOYhU7ujCDTREpbK3kar/dAOkuyfuDzbRfjXBcLORV5psvXvnqnqhkR7NP87ELHEx32b3g7PN+jwXGyNHqjBW1tcHIsaN0o/MNelfvoa3b+g5GO753w79YEnSvDAOIIIalf0ZsNbt68zLaHuGN/lB1WEXF0qo0fSzX8MHQeOPrLjyffjfvT2KRxHzjZJTx6x5+6JpPgeG1amt3mC7yDvbAbQ2oXyMOWcGT6yd/YCbX9gYalhlN0J0uVNZqpby5z1uYQnH7ZBslGSkGlLs17qKXa/k+siT+TnAO4NEAx5VJ/s7DJoJt26NKd3Vds5mVMRJOFB1oImSdN1G5MoZ2opHrTYeCPHoCUxuJOWU0PHOFmUx7rgNQUQ0R6oYAz5TcqXjBpxWb6DwQBa9rPoQc3TnExh74g4EOD5ZiPPZ5WISo/yIwyHqxa1A0eeBh7PE0nkIxPFKySV+MAgy/qjrfdCsYFHEmrqBVOp9A/fjDx+KpfgETdQiI3lK6HJ6tmb/QIPnk6eUs6sz6FIZoguCHIsj8M8K2L0wjF0LVM/78Ro1JijmxyIqWxEjOqL1Abvw6RmKg7ldEXUiVI36gstJYXoWdtbGaNrXhb9K9EznXkH68y8xZqGW5zbNxgzhx2SL+9tg8FkOU=
conda_forge_output_validation: true
